- name: Setup server configuration
  hosts: all
  become: yes
  pre_tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        name:
          - git
          - make
        update_cache: yes
  roles:
    - role: geerlingguy.postgresql
      postgresql_hba_entries:
        - { type: local, database: all, user: postgres, auth_method: trust }

    - role: geerlingguy.nodejs
      nodejs_version: "14.x"

  # также можно выполнить в рамках запуска роли geerlingguy.postgresql и настроить бд и пользователя
  # Каждое приложение будет подключаться к своей базе. В реальности они бы подключались к одной
- name: Setup database
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Create a new database with name "vagrant"
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"

    - name: Add vagrant user
      community.postgresql.postgresql_user:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: ALL
        state: present
        role_attr_flags: CREATEDB,SUPERUSER

    - name: Grant app user access
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/12/main/pg_hba.conf
        contype: host
        users: "{{ db_user }}"
        databases: "{{ db_name }}"
        method: md5
        source: "127.0.0.1"
        state: present

    - name: Reload postgrsql
      ansible.builtin.systemd:
        name: postgresql
        state: restarted

- name: Setup application
  hosts: all
  gather_facts: no
  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/hexlet-components/js-fastify-blog.git
        dest: "{{ app_dir }}"

    - name: Create .env file
      ansible.builtin.template:
        src: templates/env.j2
        dest: "{{ app_dir }}.env"

    - name: Install application dependencies
      community.general.npm:
        path: "{{ app_dir }}"
        state: present
